2017-04-16 19:04:48,105: pmgr.launching.2.child: pmgr.launching.2                : MainThread     : ERROR   : bulk launch failed
Traceback (most recent call last):
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 298, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/pmgr/launching/default.py", line 374, in _start_pilot_bulk
    session_sandbox = self._session._get_session_sandbox(pilots[0]).path
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 809, in _get_session_sandbox
    global_sandbox  = self._get_global_sandbox(pilot)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/radical/pilot/session.py", line 774, in _get_global_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthorizationFailed: read from process failed '[Errno 5] Input/output error' : (the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
) ((To access the system:

1) If not using ssh-keys, please enter your TACC password at the password prompt
2) At the TACC Token prompt, enter your 6-digit code followed by <return>.  

Authenticated with partial success.
TACC Token Code:
TACC Token Code:
TACC Token Code:
Permission denied (gssapi-keyex,gssapi-with-mic,keyboard-interactive).
)) (/home/mingtha/ve/ve.exec_model_exp/local/lib/python2.7/site-packages/saga/utils/pty_exceptions.py +49 (translate_exception)  :  e = se.AuthorizationFailed (cmsg))
2017-04-16 19:55:25,213: pmgr.launching.2.child: pmgr.launching.2                : MainThread     : ERROR   : TERM : pmgr.launching.2.child run intr
2017-04-16 19:55:25,213: pmgr.launching.2.child: pmgr.launching.2                : MainThread     : ERROR   : TERM : pmgr.launching.2.child run final
